server:
  port: 8888
spring:
  application:
    name: user-api
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://119.3.16.132:3306/imooc-security?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    generate-ddl: true
    show-sql: true
#server:
#  ssl:
#    key-store: classpath:jojo.key
#    key-store-password: 123456
#    key-password: 123456
